# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone To C:/
        run: |
          cd C:/
          git clone --depth=1 https://github.com/axojhf/mabs.git m
      - name: build
        run: |
          cd C:/m
          ./media-autobuild_suite.bat
      - uses: actions/upload-artifact@v3
        with:
          name: bin-video
          path: C:/m/local64/bin-video
      - uses: actions/upload-artifact@v3
        with:
          name: bin-audio
          path: C:/m/local64/bin-audio
