name: Multipy Steps

on:
  push:
    branches: [ "step" ]
  pull_request:
    branches: [ "step" ]
  workflow_dispatch:

jobs:
  Test0:
    runs-on: windows-2019
    steps:
      - name: Clone To C:/
        run: |
          cd C:/
          git clone --depth=1 https://github.com/axojhf/mabs.git m -b step
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            C:/m/local64
          key: mingw-step-cache
      - name: build
        run: |
          cd C:/m
          cd local64
          ls
          cd lib
          ls