name: Test

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  Test0:
    runs-on: windows-2019
    steps:
      - name: Clone To C:/
        run: |
          cd C:/
          git clone --depth=1 https://github.com/axojhf/mabs.git m -b step
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            C:\m\local64
          key: mingw-step-cache
      - name: build
        run: |
          cd C:/m
          cd local64
          ls
          cd lib
          ls
        # cp step0.ini build/media-autobuild_suite.ini
        # ./media-autobuild_suite.bat

  # #如果build0运行完成，则运行build1
  # build1:
  #   needs: build0
  #   runs-on: windows-2019
  #   steps:
  #     - name: Clone To C:/
  #       run: |
  #         cd C:/
  #         git clone --depth=1 https://github.com/axojhf/mabs.git m -b step
  #     - name: Cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           C:/m/local64
  #         key: mingw-step-cache
  #     - name: build
  #       run: |
  #         cd C:/m
  #         cp step1.ini build/media-autobuild_suite.ini
  #         ./media-autobuild_suite.bat
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: bin-video
  #         path: C:/m/local64/bin-video
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: bin-audio
  #         path: C:/m/local64/bin-audio